name: flutterpokedex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6
  get_it: ^7.2.0
  http: ^1.2.2
  provider: ^6.0.4
  json_annotation: ^4.8.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.0.5
  json_serializable: ^6.6.1
  mockito: ^5.4.0
  pedantic: ^1.11.1  
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true




